replicaCount: 1
namespace: dev
image:
  repository: registry.digitalocean.com/anyaa/hub
  tag: 73520cd
containerPort: 3000
ingress:
  tld: dev.anyaa.io
  domain: hub
  path: /
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
acme:
  email: thaer.abbas@anyaa.io
