replicaCount: 1
namespace: staging
image:
  repository: registry.digitalocean.com/anyaa/hub
  tag: 87b04fe
containerPort: 3000
ingress:
  tld: anyaa.store
  domain: hub
  path: /
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
acme:
  email: thaer.abbas@anyaa.io
