# Default values for portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

namespace: prod

image:
  repository: registry.digitalocean.com/anyaa/portal
  tag: 'latest'

containerPort: 3000

ingress:
  tld: prod.anyaa.io
  domain: portal
  path: /

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

acme:
  email: thaer.abbas@anyaa.io
