replicaCount: 2
namespace: prod
image:
  repository: registry.digitalocean.com/anyaa/hub
  tag: 1abbdbe
containerPort: 3000
ingress:
  tld: anyaa.io
  domain: hub
  path: /
resources:
  limits:
    cpu: 20m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi
acme:
  email: thaer.abbas@anyaa.io
