name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main
      - develop
      - staging

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: hub

jobs:
  #Push to Digital Ocean private Registry
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Install doctl # install the doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: push image to digitalocean
        run: |
          doctl registry login
          docker tag $IMAGE_NAME registry.digitalocean.com/anyaa/$IMAGE_NAME
          docker push registry.digitalocean.com/anyaa/$IMAGE_NAME

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: anyaa-k8s

      - name: Upgrade deployment
        run: |
          helm upgrade --install --atomic --timeout 5m $IMAGE_NAME ./infra/ -f ./infra/values-dev.yaml \
          --namespace dev --create-namespace \
          --set-string sha=${{ github.sha }}

      - name: Restart deployment
        run: kubectl rollout restart deployment $IMAGE_NAME -n dev
